services:
  bot-db:
    image: postgres:15.3-alpine3.18
    container_name: sm-bot-postgres
    command: postgres
    ports:
      - "30030:5432"
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-pass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test-user -d test-db" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      sm-web-bot:
        aliases:
          - db

  bot-migrate:
    image: migrate/migrate
    container_name: sm-bot-migrate
    volumes:
      - ../migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://test-user:test-pass@db:5432/test-db?sslmode=disable", "up" ]
    depends_on:
      bot-db:
        condition: service_healthy
    networks:
      - sm-web-bot

networks:
  sm-web-bot:
    driver: bridge
